In [9]:
import math 
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [11]:
x = [8.0, 1, 2.5, 4., 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4., 28.0]

print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4.0, 28.0]
[8.0, 1, 2.5, nan, 4.0, 28.0]


In [12]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

print(y)
print(y_with_nan)

[ 8.   1.   2.5  4.  28. ]
[ 8.   1.   2.5  nan  4.  28. ]


In [13]:
print(z)
print(z_with_nan)

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64


In [15]:
mean_ = sum(x) / len(x)
mean_

8.7

In [16]:
mean_ = statistics.mean(x)
print(mean_)

8.7


In [17]:
mean_ = statistics.mean(x_with_nan)
print(mean_)

nan


In [18]:
sum(x_with_nan)

nan

In [19]:
x_with_nan

[8.0, 1, 2.5, nan, 4.0, 28.0]

In [20]:
mean_ = np.mean(y)
mean_

8.7

In [21]:
mean_ = y.mean()
mean_

8.7

In [22]:
print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [23]:
y_with_nan.mean()

nan

In [26]:
np.nanmean(y_with_nan)

8.7

In [27]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [28]:
mean_ = z.mean()
mean_

8.7

In [30]:
z_with_nan

0     8.0
1     1.0
2     2.5
3     NaN
4     4.0
5    28.0
dtype: float64

In [29]:
z_with_nan.mean()

8.7

In [31]:
var = [2, 2, 4, 4, 4, 4, 4, 8, 8, 8]
len(var)

10

# Weighted Mean

In [47]:
(0.2*2) + (0.5*4) + (0.3*8)

4.8

In [35]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]

In [36]:
sum(w)

1.0

In [39]:
wmean = sum(w[i]*x[i] for i in range(len(x))) / sum(w)
wmean 

6.95

In [42]:
sum(x_ * w_ for (x_,w_) in zip(x,w)) / sum(w)

6.95

In [44]:
y,z,w = np.array(x), pd.Series(x), np.array(w)

wmean = np.average(y, weights=w)
wmean

6.95

In [45]:
np.average(z, weights=w)

6.95

In [46]:
(w * y).sum() / w.sum()

6.95

# Harmonic Mean

In [48]:
(60+20)/2

40.0

In [49]:
(2+4+6+100)/4

28.0

In [51]:
4 / (1/2 + 1/4 + 1/6 + 1/100)

4.316546762589928

In [52]:
statistics.harmonic_mean(x)

2.7613412228796843

In [53]:
np.mean(x)

8.7

In [54]:
x

[8.0, 1, 2.5, 4, 28.0]

In [55]:
scipy.stats.hmean(y)

2.7613412228796843

In [56]:
scipy.stats.hmean(z)

2.7613412228796843

# Geometric Mean

In [57]:
2*18

36

In [60]:
gmean = 1

for item in x:
    gmean *= item
gmean

2240.0

In [61]:
gmean**= 1 / len(x)
gmean

4.677885674856041

In [62]:
scipy.stats.gmean(y)

4.67788567485604

In [64]:
scipy.stats.gmean(z)

4.67788567485604

# Median

In [75]:
n = len(x)

if n % 2:
    median_ = sorted(x)[round(0.5*(n-1))]
else:
    x_ord,index = sorted(x),round(0.5*n)
    median_ = 0.5 * (x_ord[index-1] + x_ord[index])
    
median_

4

In [66]:
n

5

In [68]:
statistics.median_low(x[:-1])

2.5

In [69]:
statistics.median_high(x[:-1])

4

In [70]:
x[:-1]

[8.0, 1, 2.5, 4]

In [71]:
statistics.median_low(x_with_nan)

4.0

In [72]:
statistics.median_high(x_with_nan)

8.0

In [73]:
np.median(y)

4.0

In [74]:
np.median(y[:-1])

3.25

# Mode

In [76]:
u = [2, 3, 2, 8, 12]
v = [12, 15, 12, 15, 21, 15, 12]

In [77]:
max((u.count(item), item) for item in set(u))[1]

2

In [78]:
statistics.mode(u)

2

In [79]:
u, v = np.array(u), np.array(v)
scipy.stats.mode(u)

ModeResult(mode=array([2]), count=array([2]))

In [83]:
scipy.stats.mode(v)

ModeResult(mode=array([12]), count=array([3]))

In [85]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2,2,math.nan])

In [86]:
u.mode()

0    2
dtype: int32

In [87]:
v.mode()

0    12
1    15
dtype: int32

In [88]:
w.mode()

0    2.0
dtype: float64

# Measure of Variability

In [91]:
n = len(x)

mean_ = sum(x) / n

In [99]:
var_ = sum((item - mean_)**2 for item in x) / (n-1)
var_

123.19999999999999

In [93]:
statistics.variance(x)

123.2

In [94]:
np.var(y, ddof=1)

123.19999999999999

In [95]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [98]:
z.var(ddof=1)

123.19999999999999

# Standard Deviation

In [100]:
var_ ** 0.5

11.099549540409285

In [101]:
statistics.stdev(x)

11.099549540409287

In [102]:
np.std(y, ddof=1)

11.099549540409285

In [103]:
z.std(ddof=1)

11.099549540409285

# Skewness

In [104]:
x

[8.0, 1, 2.5, 4, 28.0]

In [107]:
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n-1)
std_ = var_ ** 0.5

skew_ = (sum((item - mean_)**3 for item in x)) * n / ((n-1) * (n-2) * std_**3)
skew_

1.9470432273905929

In [108]:
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [109]:
scipy.stats.skew(y_with_nan, bias=False)

nan

In [110]:
z.skew()

1.9470432273905924

In [111]:
z_with_nan.skew()

1.9470432273905924

# Percentiles 

In [114]:
x = [-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]
x

[-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

In [115]:
statistics.quantiles(x, n=2)

[8.0]

In [116]:
y = np.array(x)
np.percentile(y, 5)

-3.44

In [117]:
np.percentile(y, 95)

34.919999999999995

In [118]:
np.percentile(y, 50)

8.0

In [119]:
np.percentile(y_with_nan, 50)

nan

In [120]:
np.nanpercentile(y_with_nan, 50)

4.0

In [121]:
np.quantile(y, 0.05)

-3.44

In [122]:
np.quantile(y, 0.95)

34.919999999999995

# Ranges

In [123]:
np.ptp(y)

46.0

In [125]:
sorted(y)

[-5.0, -1.1, 0.1, 2.0, 8.0, 12.8, 21.0, 25.8, 41.0]

In [126]:
41 - (-5)

46

In [127]:
np.amax(y)

41.0

In [128]:
np.amin(y)

-5.0

In [129]:
np.amax(y) - np.amin(y)

46.0

# Summary of Descriptive Statistics

In [130]:
result = scipy.stats.describe(y, ddof=1, bias=False)
result

DescribeResult(nobs=9, minmax=(-5.0, 41.0), mean=11.622222222222222, variance=228.75194444444446, skewness=0.9249043136685094, kurtosis=0.14770623629658886)

In [131]:
result.nobs

9

In [132]:
result.minmax[1]

41.0

In [133]:
result.skewness

0.9249043136685094

In [135]:
result = z.describe()
result

count     5.00000
mean      8.70000
std      11.09955
min       1.00000
25%       2.50000
50%       4.00000
75%       8.00000
max      28.00000
dtype: float64

In [136]:
result['25%']

2.5

In [137]:
result['mean']

8.7

# Correlation

In [139]:
x = list(range(-10, 11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 5, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

In [140]:
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x), pd.Series(y)

In [147]:
n = len(x)
mean_x,mean_y = sum(x) / n,sum(y) / n

cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n)) / (n-1))
cov_xy

19.95

In [146]:
np.cov(x_, y_)

array([[38.5       , 19.95      ],
       [19.95      , 13.84761905]])

In [148]:
x_.var(ddof=1)

38.5

In [151]:
y_.var(ddof=1)

13.847619047619048

In [152]:
np.cov(x_, y_)[0, 1]

19.950000000000003

In [153]:
np.cov(x_, y_)[1, 0]

19.950000000000003

# Correlation Coefficient

In [158]:
var_x = sum((item - mean_x)**2 for item in x) / (n-1)
var_y = sum((item - mean_y)**2 for item in y) / (n-1)

std_x,std_y = var_x**0.5,var_y**0.5

r = cov_xy / (std_x * std_y)
r

0.8640223596581549

In [159]:
scipy.stats.pearsonr(x_, y_)

(0.8640223596581549, 4.474769296697294e-07)

In [160]:
np.corrcoef(x_, y_)

array([[1.        , 0.86402236],
       [0.86402236, 1.        ]])

In [161]:
np.corrcoef(x_, y_)[0,1]

0.864022359658155

In [162]:
scipy.stats.linregress(x_, y_)

LinregressResult(slope=0.5181818181818182, intercept=5.619047619047619, rvalue=0.864022359658155, pvalue=4.474769296697264e-07, stderr=0.06926912433136921, intercept_stderr=0.41944537761978634)

In [163]:
scipy.stats.linregress(x_, y_).rvalue

0.864022359658155

In [164]:
scipy.stats.linregress(x_, y_).pvalue

4.474769296697264e-07

y = mx+c

In [165]:
x__.corr(y__)

0.864022359658155

In [166]:
y__.corr(x__)

0.864022359658155

# 2D Data

In [167]:
a = np.array([[1,1,1],
         [2,3,1],
          [4,9,2],
          [8,27,4],
          [16,1,1]
         ])

In [168]:
a

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [169]:
np.mean(a)

5.4

In [170]:
a.mean()

5.4

In [171]:
np.median(a)

2.0

In [172]:
np.mean(a, axis=0)

array([6.2, 8.2, 1.8])

In [173]:
np.mean(a, axis=1)

array([ 1.,  2.,  5., 13.,  6.])

In [174]:
scipy.stats.gmean(a)

array([4.        , 3.73719282, 1.51571657])

In [175]:
scipy.stats.gmean(a, axis=1)

array([1.        , 1.81712059, 4.16016765, 9.52440631, 2.5198421 ])

In [176]:
scipy.stats.gmean(a, axis=None)

2.829705017016332

In [178]:
scipy.stats.describe(a, axis=1, ddof=1, bias=False)

DescribeResult(nobs=3, minmax=(array([1, 1, 2, 4, 1]), array([ 1,  3,  9, 27, 16])), mean=array([ 1.,  2.,  5., 13.,  6.]), variance=array([  0.,   1.,  13., 151.,  75.]), skewness=array([0.        , 0.        , 1.15206964, 1.52787436, 1.73205081]), kurtosis=array([-3. , -1.5, -1.5, -1.5, -1.5]))

# Dataframe

In [179]:
row_names = ['first', 'second', 'third', 'fourth', 'fifth']
col_names = ['A', 'B', 'C']

df = pd.DataFrame(a, index=row_names, columns=col_names)
df

A   B  C
first    1   1  1
second   2   3  1
third    4   9  2
fourth   8  27  4
fifth   16   1  1

In [180]:
df.mean()

A    6.2
B    8.2
C    1.8
dtype: float64

In [181]:
df.var()

A     37.2
B    121.2
C      1.7
dtype: float64

In [182]:
df.mean(axis=1)

first      1.0
second     2.0
third      5.0
fourth    13.0
fifth      6.0
dtype: float64

In [183]:
df["A"]

first      1
second     2
third      4
fourth     8
fifth     16
Name: A, dtype: int32

In [184]:
df["A"].mean()

6.2

In [185]:
df["A"].var()

37.20000000000001

In [186]:
df.values

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [187]:
df.to_numpy()

array([[ 1,  1,  1],
       [ 2,  3,  1],
       [ 4,  9,  2],
       [ 8, 27,  4],
       [16,  1,  1]])

In [188]:
df.describe()

A          B        C
count   5.00000   5.000000  5.00000
mean    6.20000   8.200000  1.80000
std     6.09918  11.009087  1.30384
min     1.00000   1.000000  1.00000
25%     2.00000   1.000000  1.00000
50%     4.00000   3.000000  1.00000
75%     8.00000   9.000000  2.00000
max    16.00000  27.000000  4.00000